

services:
  dhqanh-server:
    image: dhqanh-server:latest
    ports:
      - "8088:8088"
    restart: unless-stopped

    env_file:
      - app.env

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
