version: "3.9"

services:
  bpm-server:
    image: giangtheshy/bpm-be:latest
    restart: unless-stopped
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    container_name: server-bpm
    volumes:
      - ./app.env:/go/src/run/app.env
    ports:
      - 8088:8088
    env_file:
      - app.env
    networks:
      - bpm-api
  
networks:
  bpm-api:
    driver: bridge